import CustomDump
import Foundation
import Testing
@testable import TrackingGenerator

@Suite("SwiftCodeGenerator")
struct SwiftCodeGeneratorTests {
    struct Locations {
        @Test func `generateLocationCode produces enum with expected cases and comments`() throws {
            let locations: [LocationDefinition] = [
                .init(id: "activity"),
                .init(id: "check_in_intent", description: "Intents are an iOS specific feature"),
                .init(id: "not_applicable", description: "It's a generic location to indicate NO location"),
            ]

            let generator = SwiftCodeGenerator(locations: locations, events: [])

            let code = try generator.generateLocationCode()

            expectNoDifference(
                code,
                """
                // DO NOT EDIT - This file is autogenerated

                // swiftlint:disable type_body_length file_length vertical_whitespace

                import Foundation

                public enum TrackingLocation: String {
                    case activity

                    /// Intents are an iOS specific feature
                    case checkInIntent = "check_in_intent"

                    /// It's a generic location to indicate NO location
                    case notApplicable = "not_applicable"
                }

                // swiftlint:enable type_body_length file_length vertical_whitespace

                """
            )
        }
    }

    struct Events {
        @Test func `generating simple events`() throws {
            let events: [EventDefinition] = [
                .init(name: "switch_to_find_club_map"),
            ]

            let generator = SwiftCodeGenerator(locations: [], events: events)

            let code = try generator.generateEventCode()

            expectNoDifference(
                code,
                """
                // DO NOT EDIT - This file is autogenerated

                // swiftlint:disable type_body_length file_length vertical_whitespace function_parameter_count

                import Foundation

                public extension TrackingEvent {
                    static func switchToFindClubMap(from location: TrackingLocation) -> TrackingEvent {
                        .init(event: "switch_to_find_club_map", location: location)
                    }
                }

                // swiftlint:enable type_body_length file_length vertical_whitespace function_parameter_count

                """
            )
        }

        @Test func `generated event with parameters and description`() throws {
            let events: [EventDefinition] = [
                .init(
                    name: "open_club_profile",
                    parameters: [
                        "club_name",
                    ],
                    description: "Opening the club profile screen for the given club"
                ),
            ]

            let generator = SwiftCodeGenerator(locations: [], events: events)

            let code = try generator.generateEventCode()

            expectNoDifference(
                code,
                """
                // DO NOT EDIT - This file is autogenerated

                // swiftlint:disable type_body_length file_length vertical_whitespace function_parameter_count

                import Foundation

                public extension TrackingEvent {
                    /// Opening the club profile screen for the given club
                    static func openClubProfile(
                        clubName: String,
                        from location: TrackingLocation
                    ) -> TrackingEvent {
                        .init(
                            event: "open_club_profile",
                            location: location,
                            parameters: [
                                "club_name": clubName,
                            ]
                        )
                    }
                }

                // swiftlint:enable type_body_length file_length vertical_whitespace function_parameter_count

                """
            )
        }

        @Test func `generating events with default location`() throws {
            let events: [EventDefinition] = [
                .init(name: "switch_to_find_club_map"),
                .init(name: "open_feed", defaultLocation: .init(id: "activity")),
                .init(name: "test_event_with_params", parameters: ["is_this_true"], defaultLocation: .init(id: "check_in_intent")),
            ]

            let generator = SwiftCodeGenerator(locations: [], events: events)

            let code = try generator.generateEventCode()

            expectNoDifference(
                code,
                """
                // DO NOT EDIT - This file is autogenerated

                // swiftlint:disable type_body_length file_length vertical_whitespace function_parameter_count

                import Foundation

                public extension TrackingEvent {
                    static func switchToFindClubMap(from location: TrackingLocation) -> TrackingEvent {
                        .init(event: "switch_to_find_club_map", location: location)
                    }

                    static func openFeed(from location: TrackingLocation = .activity) -> TrackingEvent {
                        .init(event: "open_feed", location: location)
                    }

                    static func testEventWithParams(
                        isThisTrue: String,
                        from location: TrackingLocation = .checkInIntent
                    ) -> TrackingEvent {
                        .init(
                            event: "test_event_with_params",
                            location: location,
                            parameters: [
                                "is_this_true": isThisTrue,
                            ]
                        )
                    }
                }

                // swiftlint:enable type_body_length file_length vertical_whitespace function_parameter_count

                """
            )
        }
    }
}
